name: ci # Name of the Action.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] # When this action runs.

jobs:
  build:

    runs-on: ubuntu-latest # Which OS this runs on, you can also build on Windows or MacOS.

    steps:
    - uses: actions/checkout@v4 # Calling a pre-built GitHub Action which allows your Action to access your repository.
    - name: Set up Python # Name of an action that sets up Python.
      uses: actions/setup-python@v3 # A pre-built GitHub Action that sets up a Python environment.
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r src/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest  # Final action which runs pytest. If any test fails, then this Action fails.
      run: |
        pytest test_app.py --verbose
        pytest test_model.py --verbose
